### PR TITLE
Issue#91

### PR DESCRIPTION
**Pull request by coleweusthem**
This pull request corrects accessibility issues with header order.

### CODE REVIEW

**Comment by nfee006** [comment]
Thanks @coleweusthem  - looks great overall. A few small things:

image

1. There seems to be an error in the search page breadcrumbs in French ("built-in method title [...]"). 
2.  This is my mistake: there's a slight typo in the title on the French search page - the "L" in "L'ASC" should not be capitalized. The title should read "Portail du gouvernement ouvert de l'ASC"
3. There are 2 H1 on the search page (title and # of datasets). Would it be possible to correct this please? Feel free to change the heading level for other elements on the page if you need to. 

Everything else looks good.

**Comment by coleweusthem** [comment]
Apologies, I didn't see the breadcrumb issue in french. I'll correct those other 2 issues as well.

**Comment by coleweusthem** [comment]
@nfee006 those issues should be corrected now. I let the css rules in place change the style of the headers. If you'd like them not to change let me know and I'll write some CSS to enforce style before the change.

**Comment by nfee006** [comment]
Looks good, thanks.

**Pull request merged**
